'use client';

import { use, useEffect, useState } from 'react';
import { CheckCircle2, Loader2 } from 'lucide-react';

interface PublicTask { title: string; description: string; dueDate: string; status: string; taskType: string; assignees: string[]; completedByEmail: string | null; }
export default function CompleteTaskPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const [task, setTask] = useState<PublicTask | null>(null); const [email, setEmail] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/tasks/complete/${token}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setTask(data); setEmail(data.assignees[0] || ''); }).catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, [token]);
  const complete = async () => { setSaving(true); setError(''); try { const response = await fetch(`/api/tasks/complete/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setTask((current) => current ? { ...current, status: 'COMPLETED', completedByEmail: data.completedByEmail } : current); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to complete task.'); } finally { setSaving(false); } };
  return <main className="flex min-h-screen items-center justify-center p-4"><section className="glass-panel w-full max-w-xl rounded-2xl border border-white/10 p-6 sm:p-8">{loading ? <Loader2 className="mx-auto animate-spin text-indigo-400" /> : error && !task ? <p className="text-center text-red-400">{error}</p> : task && <><p className="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-400">SGIC Assigned Task</p><h1 className="mt-3 text-2xl font-bold text-white">{task.title}</h1><p className="mt-2 text-sm text-slate-400">{task.taskType} · Due {new Date(task.dueDate).toLocaleString()}</p><div className="mt-5 whitespace-pre-wrap rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-relaxed text-slate-300">{task.description || 'No description provided.'}</div>{task.status === 'COMPLETED' ? <div className="mt-6 flex items-center gap-3 rounded-xl border border-emerald-500/25 bg-emerald-500/10 p-4 text-emerald-300"><CheckCircle2 /><span>Completed{task.completedByEmail ? ` by ${task.completedByEmail}` : ''}</span></div> : <div className="mt-6 space-y-3"><label className="block text-xs font-semibold text-slate-300">Confirm your assignee email<select value={email} onChange={(event) => setEmail(event.target.value)} className="dashboard-control mt-2 w-full rounded-lg border px-3 py-2.5 text-sm">{task.assignees.map((assignee) => <option key={assignee}>{assignee}</option>)}</select></label>{error && <p className="text-xs text-red-400">{error}</p>}<button type="button" disabled={saving || !email} onClick={complete} className="dashboard-primary-button flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 font-semibold text-white disabled:opacity-50">{saving ? <Loader2 size={17} className="animate-spin" /> : <CheckCircle2 size={17} />}Mark as Completed</button></div>}</>}</section></main>;
}
